### PR TITLE
Add styling

### PR DESCRIPTION
**Pull request by zeff96**
Add main.scss file to the doc,
Add position property to properly arrange elements,
Add font family to the doc.

### CODE REVIEW

**Review by muneebulrehman — CHANGES_REQUESTED** [review]
Hi @zeff96 , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Descriptive PR
- Followed wireframe styling

## Required Changes ♻️
_Check the comments under the review._

- [ ] As per the project requirements, in your README file, you need to mention the API that your application is consuming. In your case, your application is consuming the Leaderboard API provided to you by Microverse. Kindly add the link of the API in your README file, mentioning that your application is using this particular API to store and fetch data.

## Optional suggestions

- Consider removing the **Live Demo** section from your README file, since you have not deployed the project online.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zeff96** [comment]
Hi @muneebulrehman ,
I did some checks on the changes you proposed, couldn't find that requirement to mention API being consumed on README. mind a screenshot, please.

**Review by ShadyShawkat — APPROVED** [review]
## Hi @zeff96, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- All linters are passing ✔️ 
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by muneebulrehman** [comment]
> Hi @muneebulrehman , I did some checks on the changes you proposed, couldn't find that requirement to mention API being consumed on README. mind a screenshot, please.

Sure @zeff96 , here you go ⬇️
image

**Comment by zeff96** [comment]
@muneebulrehman ,

Thanks got it, updated it as required,

**Pull request merged**
